---

- name: ensure debian default xbacklight is uninstalled
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages:
      - xbacklight

- name: ensure wavexx xbacklight is downloaded
  get_url:
    url: https://raw.githubusercontent.com/wavexx/acpilight/master/xbacklight
    dest: "{{ xbacklight_path }}"
    mode: 0755
    force: True
    timeout: 30
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: True

- name: ensure udev is installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - udev

- name: ensure udev rules directory exist
  file:
    path: "{{ xbacklight_udev_rules_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: True

- name: ensure udev rules are present
  copy:
    src: files/90-backlight.rules
    dest: "{{ xbacklight_udev_rules_dir }}/90-backlight.rules"
    owner: root
    group: root
    mode: 0644
  become: True

- name: set username
  command: whoami
  register: xbacklight_username
  check_mode: False
  changed_when: False

- name: ensure user is added to video group
  user:
    name: "{{ xbacklight_username.stdout }}"
    groups: video
    append: True
    update_password: on_create
  become: True
