---

# 'install', 'remove' or 'ignore'
network_manager: 'ignore'

network_manager_plugin_openvpn: True
network_manager_plugin_l2tp: False
network_manager_plugin_openconnect: False
network_manager_plugin_pptp: False
network_manager_plugin_ssh: False
network_manager_plugin_strongswan: False
network_manager_plugin_vpnc: False

network_manager_nm_applet: True
