---

- name: ensure clipmenu requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ clipmenu_shared_packages }}"

- name: ensure clipmenu is downloaded
  get_url:
    url: "https://raw.githubusercontent.com/cdown/clipmenu/develop/{{ item }}"
    dest: "{{ clipmenu_bin_path }}/{{ item }}"
    mode: 0755
    force: True
    timeout: 30
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: True
  with_items:
    - clipmenu
    - clipmenud
