---

- name: make sure workspace rsync installed in remote
  include_role:
    name: ws-rsync
  vars:
    ws_rsync: "install"

- name: create backup service dir
  become: True
  file:
    path: "/etc/backup"
    state: directory
    mode: 0755

- name: Uploading timer file
  become: True
  template:
    src: templates/timemachine.j2
    dest: "/etc/backup/{{ item.value.timer_command | basename }}"
    mode: 0640
  with_dict: "{{ timers }}"

- name: Bringing up timer serivce
  become: True
  include_role:
    name: systemd-timers

