---

- name: ensure workspace rsync requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ ws_rsync_shared_packages }}"

- name: ensure linux timemachine is downloaded
  get_url:
    url: https://raw.githubusercontent.com/kevintruong/workspace-rsync/master/ws-rsync
    dest: "{{ ws_rsync_path }}"
    mode: 0755
    force: True
    timeout: 30
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: True
