---

- name: ensure terraform is removed
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ terraform_path }}/terraform"
    - "{{ terraform_bash_completion_path }}/terraform"
  become: True
