---

- name: ensure requirements openvpn are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ openvpn-client-package }}"

- name: deploy openvpn client credentials file
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/root/.oh-my-zsh
  become: True
