---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ openvpn-client-package }}"

- name: install vpn-client
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/root/.oh-my-zsh
  become: True

- name: Create conf folder in home directory
  file: path=/root/conf/ state=directory owner=root
  become: True

- name: deploy .zshrc
  template: src=../files/zshrc.in dest=/root/conf/zshrc owner=root
  become: True

- name: remove standard zshrc
  file: path=/root/.zshrc state=absent
  become: True

- name: symlink zshrc
  file: path=/root/.zshrc src=/root/conf/zshrc state=link owner=root force=true
  become: True

- name: Set zsh as default shell
  user: name=root shell=/bin/zsh
  become: True
