---
- name: Install openvpn
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ openvpn_client_package }}"

- name: create openvpn client dir
  file:
    path: "{{ openvpn_client_conf_dir }}"
    state: directory
    owner: whoami
    group: whoami
    mode: 0755

- name: copy auth password file
  template:
    src: templates/auth.txt.j2
    dest: "{{ openvpn_client_conf_dir }}/{{ openvpn_client_conf_file | basename | splitext | first }}-auth.txt"

- name: upload vpn client to openvpn conf dir on the remote hosts
  synchronize:
    src: "{{ openvpn_client_conf_file }}"
    dest: "{{ openvpn_client_conf_dir }}/{{ openvpn_client_conf_file | basename }}"


- name: change conf file with auth file
  lineinfile:
    dest: "{{ openvpn_client_conf_dir }}/{{ openvpn_client_conf_file | basename }}"
    regexp: '^auth-user-pass'
    line: 'auth-user-pass {{ openvpn_client_conf_file | basename | splitext | first }}-auth.txt'

- name: enable and start service
  systemd:
    name: "openvpn@{{ openvpn_client_conf_file | basename | splitext | first }}"
    state: started
    enabled: yes

