---

- name: VPN client
  user: name=root shell=/bin/bash
  become: True

- name: ensure requirements are removed
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages: "{{ openvpn-client-package }}"

- name: remove zshrc and oh-my-zsh base path
  file: path=/root/.oh-my-zsh state=absent
  become: True
