---

- name: ensure neovim is installed
  include_role:
    name: apt-meta
  vars:
    apt_packages: "{{ [neovim_package_name] + neovim_shared_packages + neovim_exclusive_packages }}"

- name: ensure neovim python packages are installed
  include_role:
    name: python-meta
  vars:
    python_2_apt_packages: "{{ neovim_python2_packages }}"
    python_3_apt_packages: "{{ neovim_python3_packages }}"
