---

- name: ensure diff-highlight is downloaded
  get_url:
    url: https://raw.githubusercontent.com/K-Phoen/Config/master/bin/diff-highlight
    dest: "{{ diff_highlight_path }}"
    mode: 0755
    force: True
    timeout: 30
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: True
