---

# 'install', 'remove' or 'ignore'
fzf: 'ignore'

# Add sourcing ~/.fzf.bash to your normal shell config?
fzf_update_rc: True

# Enable/Disable fuzzy completion (bash & zsh)?
fzf_completion: False

# Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)?
fzf_key_bindings: False
